### ISSUE TITLE
DropletCreateActivity crash

### ISSUE THREAD

**Issue by karanbalani** [coding-blocks/DigitalOceanApp#102]
Actual behaviour:
- There is one/more blank droplet option which causes the activity to terminate due to resource not found.

Screenshot:
- 
![whatsapp image 2018-07-21 at 12 43 42 am](https://user-images.githubusercontent.com/29383381/43020953-8f7e36e8-8c7f-11e8-9af8-1bb435698ae1.jpeg)

Logcat:
- 07-21 00:40:28.000 12721-12721/in.tosc.digitaloceanapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.tosc.digitaloceanapp, PID: 12721
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
        at android.content.res.Resources.getDrawable(Resources.java:819)
        at android.content.Context.getDrawable(Context.java:605)
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
        at in.tosc.digitaloceanapp.adapters.ImageAdapter.selectImage(ImageAdapter.java:113)
        at in.tosc.digitaloceanapp.adapters.ImageAdapter$1.onClick(ImageAdapter.java:75)
        at android.view.View.performClick(View.java:6314)
        at android.view.View$PerformClick.run(View.java:24790)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:460)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by 4lch4** [comment]
I have some spare time so I'll fire up Android Studio and see if I can't fix this and submit a PR.

**Comment by 4lch4** [comment]
Unfortunately, this wasn't as easy of a fix as I'd hoped. I've kept my changes stashed in case no one else gets to this, I can continue work tomorrow.

**Comment by firefinchdev** [comment]
@championswimmer 
Solved #103 
Pls Review
